apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: default
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
  - name: back-service
    protocol: TCP
    port: 8500
    targetPort: 8500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  namespace: default
  labels:
    app:  backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app:  backend
    spec:
      containers:
      - name: backend
        image: susguzman/backend:0.1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: ORACLE_USER
            value: appuser
          - name: ORACLE_PASS
            value: holamundo
          - name: ORACLE_CONNSTR
            value: db-service:1521/xepdb1
        ports:
        - containerPort: 8500
          name:  backend
